### ISSUE TITLE
NOT WORKING!!!!!

### ISSUE THREAD

**Issue by tosunkaya** [CSCI3100/monopoly#1]
NOT WORKING!!! PLEASE HELP ME!! FACEBOOK CONNECT. I CHANGED. BUT AL OT OF ERRORS.
SQLSTATE[42S22]: Column not found: 1054 Unknown column 'displayName' in 'where clause'

**Comment by tinghim** [comment]
how can u find us？

**Comment by tosunkaya** [comment]
never mind. i love your project. and uploaded to my server. monopoly.bedavanetapk.com/mono PLEASE HELP ME!! I UPLOADED YOUR SQL to my phpmyadmin (
my db name: semiyeto_mono my username: semiyeto_mono my pass: my pass :)

AND EDITED FACEBOOK LOGIN AND REG PAGES TO I CREATED FACE APP and edited.

THEN I EDITED DATABASE.PHP BUT NOT WORKED: PLEASE HELP ME WITH DATABASE EDITING. THE REGISTERING AND FACEBOOK LOGIN ISNT WORKING: PLEASE HELPING: I WILL TRANSLATE ALL THE GAME AND WE WILL PLAY ON FRIENDS. HELP PLZ.
monopoly.bedavanetapk.com/mono please help me.

my database php file:

<?php 

$server = 'localhost';
$username = 'semiyeto_mono';
$password = 'MY PASSWORD';
$db = 'semiyeto_mono';

$config = array(
    'host'      => $server,
    'username'  => $username,
    'password'  => $password,
    'dbname'    => $db
);
//connecting to the database by supplying required parameters
try{
    $db = new PDO('mysql:host=' . $config['host'] . ';dbname=' . $config['dbname'], $config['username'], $config['password'],
                    array(PDO::MYSQL_ATTR_INIT_COMMAND => "SET NAMES 'utf8'"));
} catch (PDOException $e){
    die($e->getMessage());
}
$db->setAttribute(PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION);
?>

**Comment by frmok** [comment]
This project is no longer active and we do not forsee there's any chance we'll resume on further develop this. I appreciate the effort you made to set this up. I also notice you are keen on some monopoly projects and I think you can simply give up on this and move on to others. Cheers.

**Comment by andymok221** [comment]
Thanks for showing interest in our project but it is just a small course project and somehow already one year ago. Therefore, we wouldn't try to fix any bugs or further develop it. I notice that you are interested in projects about Monopoly and so I recommend you move on to the other one instead of dealing with this one.
